-- ============================================================================
-- 02_pipeline_run_phase1.sql — dbt run, phase 1 (features)
-- Traces to: FR-OPS-02, LLD Module 10 §2, docs/05-Epics.md EPIC-SKELETON §4.3
-- Jira: SH-15 (S-DBT-1), SH-20 (S-DBT-2), SH-24 (S-DBT-3), SH-26 (S-DBT-4)
-- Status: NOT YET BUILT — placeholder until the dbt project is scaffolded.
--
-- Will run:
--   dbt run --exclude tag:inference+
--   dbt test --exclude tag:inference+
-- (builds Raw -> Standardized -> Consumption -> FEAST, excluding anything
-- that references a not-yet-trained model)
-- ============================================================================
