predictive_maintenance_dbt:
  outputs:
    dev:
      account: IQWYCFG-OAC98123
      authenticator: oauth_authorization_code
      database: SNOWCOMOTIVE
      role: SNOWCOMOTIVE_ROLE
      schema: RAW
      threads: 1
      type: snowflake
      user: CHIRAJ
      warehouse: SNOWCOMOTIVE_WH

  target: dev
